apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: demo
data:
  COMPANY_NAME: INTERSWITCHER
  DEMO_NAME: ERNEST
  SERVER_PORT: "60000"
  COMPANY_AWESOME: "true"
  COMPANY_URL: "https://example.com"
  SPRING_PROFILE: docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: demo:1.0
        name: demo
        envFrom:
        - configMapRef:
            name: demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - port: 60000
    protocol: TCP
    targetPort: 60000
    nodePort: 32001
  selector:
    app: demo
  type: NodePort
status:
  loadBalancer: {}